spring:
  application:
    name: consumer

  data:
    mongodb:
      username: wasya
      password: wasya
      host: localhost
      port: 27017
      database: evggenn
      authentication-database: admin


  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: MyGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "*"